import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="luxury"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="m-0 min-h-screen flex flex-col">
        <ClerkProvider>
          <div className="min-h-screen">
            <Navbar />
          </div>
          <main className="py-8">
            {/* Container to center the conetent */}
            <div className="max-w-7xl mx-auto px-4">
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                <div className="hidden lg:block lg:col-span-3"></div>
                  Sidebar
              </div>
              <div className="lg:col-span-9">
                {children}
              </div>

            </div>
            
          </main>
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
